---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Sample Cert Creation'
Parameters:
  HostedZoneId:
    Type: String
    Description: The Route53 HostedZone which should be used for the certificate and website urls
    Default: Z00000000AZD0FWVZH0RA
  WebSiteURL:
    Type: String
    Default: certificate.kbild.ch
  Region:
    Type: String
    Default: us-east-1
    Description: The region in which to you want to deploy the certificate
    AllowedValues:
      - 'us-east-1'
      - 'us-east-2'
      - 'us-west-1'
      - 'us-west-2'
      - 'af-south-1'
      - 'ap-east-1'
      - 'ap-south-1'
      - 'ap-northeast-1'
      - 'ap-northeast-2'
      - 'ap-southeast-1'
      - 'ca-central-1'
      - 'eu-central-1'
      - 'eu-west-1'
      - 'eu-west-2'
      - 'eu-west-3'
      - 'eu-south-1'
      - 'eu-north-1'
      - 'me-south-1'
      - 'sa-east-1'
Resources:
  CustomResourceCertificate:
    Type: 'Custom::CreateCertificate'
    Properties:
      ServiceToken: !ImportValue LambdaCallStateMachineCertArn
      WebSiteURL: !Ref WebSiteURL
      HostedZoneId: !Ref HostedZoneId
      Region: !Ref Region
Outputs:
  CustomResourceCertificate:
    Value: !Ref  CustomResourceCertificate
    Export:
      Name: CustomResourceCertificate